### ISSUE TITLE
chatbot meetup 22

### ISSUE THREAD

**Issue by louis70109** [Chatbot-Taiwan/meetups#2]
溫明輝➡️《LINE API 與 UX 入門課程分享》Chatbot User Experience Design 
NiJia Lin ➡️LINE API Update 202008  https://speakerdeck.com/line_developers_tw/line-api-platform-update-202008

Chatbot meetup 22 event:https://chatbots.kktix.cc/events/meetup-022

**Comment by iitsmel** [comment]
溫明輝➡️《LINE API 與 UX 入門課程分享》Chatbot User Experience Design
NiJia Lin ➡️LINE API Update 202008 https://speakerdeck.com/line_developers_tw/line-api-platform-update-202008
陳佳新 ➡️ 用 liff.shareTargetPicker 分享我的名片（電話及網址可點擊）https://www.slideshare.net/jarsing/lightning-talk-linebizcard20200827

Chatbot meetup 22 event:https://chatbots.kktix.cc/events/meetup-022

**Comment by louis70109** [comment]
Close because https://github.com/Chatbot-Taiwan/meetups/pull/4
